project_id = "ekqgsyzxkkrlgzhavnoy"

[functions.send-order-email]
verify_jwt = false

[functions.send-part-request-email]
verify_jwt = false

[functions.send-email-verification-otp]

[functions.update-user-email]
verify_jwt = false

[functions.create-order]
verify_jwt = false
