project_id = "ekqgsyzxkkrlgzhavnoy"

[functions.send-order-email]
verify_jwt = false

[functions.send-part-request-email]
verify_jwt = false

[functions.send-email-verification-otp]
verify_jwt = false
