#!/usr/bin/env python3
"""
import-products.py
==================
Clears the categories + products tables and re-imports all 11,933
products from dmarket_products_mapped.csv into the local Docker
PostgreSQL database.

Usage:
    python import-products.py

Requirements:
    psycopg2  (already installed via Anaconda from import_spare_parts.py)

What this script does:
    1. Clears: wishlist, reviews, product_colors, product_part_types,
               order_items (product rows), products, categories
    2. Inserts the 6 valid app categories into the categories table
    3. Reads dmarket_products_mapped.csv (generated by map_categories.py)
    4. Inserts all products with correct category_id references
    5. Prints a summary with counts per category
"""

import csv
import psycopg2
from psycopg2.extras import execute_values

# ── DB connection (matches .env) ──────────────────────────────────────────────
DB_CONFIG = {
    'host':     'localhost',
    'port':     5433,
    'database': 'mydatabase',
    'user':     'admin',
    'password': '123456',
}

INPUT_FILE = 'dmarket_products_mapped.csv'

# ── 6 valid app categories (must match exactly) ───────────────────────────────
VALID_CATEGORIES = [
    "Mobile Accessories",
    "Laptop Accessories",
    "Computer Accessories",
    "New & Used Phones",
    "Mobile Spare Parts",
    "Laptop & Computer Spare Parts",
]

# ── accessory_subcategory: CHECK constraint allows only these values ───────────
# CHECK: NULL | 'mobile' | 'laptop' | 'pc' | 'computer'
MAPPED_CAT_TO_SUBCATEGORY = {
    "Mobile Accessories":            "mobile",
    "Mobile Spare Parts":            "mobile",
    "New & Used Phones":             None,       # phones are not accessories
    "Laptop Accessories":            "laptop",
    "Laptop & Computer Spare Parts": "laptop",
    "Computer Accessories":          "computer",
}

# ── Brand extraction ──────────────────────────────────────────────────────────
# These suffixes appear in raw category names like "Samsung Galaxy LCD Panel Unit"
# Strip the suffix to get the brand prefix.
_BRAND_SUFFIXES = [
    " LCD Panel Unit",
    " Phones",
    " Tablet",
    " Tablets",
]

# Raw categories where first-word extraction is wrong — override manually
_CATEGORY_BRAND_OVERRIDE = {
    "Apple iPhones":            "Apple",
    "Samsung Galaxy Phones":    "Samsung",
    "Samsung Galaxy LCD Panel Unit": "Samsung",
    "Google Pixel Phones":      "Google",
    "Google Pixel LCD Panel Unit": "Google",
    "Sharp Aquos Phones":       "Sharp",
    "Sharp Aquos LCD Panel Unit": "Sharp",
    "Sony Xperia Phones":       "Sony",
    "Sony Xperia LCD Panel Unit": "Sony",
    "Nothing Phone LCD Panel Unit": "Nothing",
    "T-Mobile Phones":          "T-Mobile",
    "Other Brand Phones":       "Various",
    "Gaming Mobile":            "Various",
    "Used Mobile":              "Various",
    "Mobile Batteries":         None,   # extract from title
    "Mobile Touch Glass":       None,
    "Sim Tray Jacket":          None,
    "Charging Port":            None,
    "Charging Connector":       None,
    "Back Camera Glass Lens":   None,
    "Back Panel Glass":         None,
    "Back Rear Cameras Modules": None,
    "Front Cameras Modules":    None,
    "Camera Modules":           None,
    "Camera Lift Motor":        None,
    "Motherboard Flex Strip":   None,
    "Motherboard":              None,
    "Power Button & Volume Button Flex": None,
    "Side Keys Button":         None,
    "LCD Display Connectors":   None,
    "LCD Display Flex Cable":   None,
    "Loud Speakers Ringtone Buzzer": None,
    "Earpieces Ear Speaker":    None,
    "Fingerprint Sensor Flex":  None,
    "Fingerprint Sensor Scanner": None,
    "Sensor Flex":              None,
    "Handsfree Jack":           None,
    "SIM Card Reader Socket":   None,
    "S Pen":                    "Samsung",
    "Complete Housing Casing":  None,
    "Spin Axis Flex Cable":     None,
    "Smart Watch Touch Glass":  None,
    "Tablet Touch Glass":       None,
    "Tablet Batteries":         None,
    "Tablet Charging Port":     None,
    "Tablet LCD Panel Unit":    None,
    "Tablet Loud Speaker":      None,
    "Tablet Motherboard Flex Strips": None,
    "Cleaner Tools":            "Various",
    "Laptop Charger":           None,
    "Laptop Batteries":         None,
}

def extract_brand(title: str, raw_category: str) -> str:
    """
    Determine brand name.
    Priority: override map → suffix stripping → title first word.
    """
    # 1. Check override map
    override = _CATEGORY_BRAND_OVERRIDE.get(raw_category)
    if override is not None:
        return override

    # 2. Strip known suffix from raw_category to get brand
    for suffix in _BRAND_SUFFIXES:
        if raw_category.endswith(suffix):
            brand = raw_category[:-len(suffix)].strip()
            if brand:
                # "Samsung Galaxy" → "Samsung", "OnePlus" → "OnePlus"
                return brand.split()[0]

    # 3. Fall back to first word of title
    words = title.strip().split()
    return words[0] if words else "Unknown"


# ── Helper converters ─────────────────────────────────────────────────────────

def to_bool(val: str) -> bool:
    return str(val).strip().lower() in ("true", "1", "yes")

def to_num(val: str):
    """Return float or None."""
    v = str(val).strip()
    if not v or v.lower() in ("none", "nan", ""):
        return None
    try:
        return float(v)
    except ValueError:
        return None

def to_path_list(val: str) -> list:
    """Split pipe-separated image paths; normalise backslashes."""
    if not val or not val.strip():
        return []
    return [
        p.strip().replace("\\", "/")
        for p in val.split("|")
        if p.strip()
    ]

def build_description(row: dict):
    """Combine description + key_features columns into one string."""
    fields = [
        "description",
        "key_features_product",
        "key_features_quality",
        "key_features_installation",
        "key_features_delivery",
        "key_features_warranty",
    ]
    parts = [row.get(f, "").strip() for f in fields if row.get(f, "").strip()]
    return " | ".join(parts) if parts else None


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    print("=" * 60)
    print("  import-products.py")
    print("  Importing products into local Docker PostgreSQL")
    print("=" * 60)

    # ── Connect ───────────────────────────────────────────────────────────────
    print("\n[1/5] Connecting to PostgreSQL (localhost:5433)...")
    try:
        conn = psycopg2.connect(**DB_CONFIG)
    except psycopg2.OperationalError as e:
        print(f"\nERROR: Cannot connect to PostgreSQL.\n{e}")
        print("\nMake sure Docker is running and the containers are up:")
        print("  npm run docker:up")
        return
    conn.autocommit = False
    cur = conn.cursor()
    print("  Connected.")

    try:
        # ── Step 2: Clear existing data ───────────────────────────────────────
        print("\n[2/5] Clearing existing categories + products data...")

        # Clear leaf tables first (reverse FK order)
        cur.execute("DELETE FROM wishlist WHERE TRUE")
        cur.execute("DELETE FROM reviews WHERE TRUE")
        cur.execute("DELETE FROM product_colors WHERE TRUE")
        cur.execute("DELETE FROM product_part_types WHERE TRUE")
        # order_items may reference products — null out or delete
        cur.execute("DELETE FROM order_items WHERE product_id IS NOT NULL")
        cur.execute("DELETE FROM products WHERE TRUE")
        cur.execute("DELETE FROM categories WHERE TRUE")

        cur.execute("SELECT COUNT(*) FROM products")
        remaining = cur.fetchone()[0]
        print(f"  Cleared. Products remaining: {remaining}")

        # ── Step 3: Insert 6 categories ───────────────────────────────────────
        print("\n[3/5] Inserting 6 valid categories...")
        cat_uuid_map = {}   # "Mobile Spare Parts" → UUID

        for name in VALID_CATEGORIES:
            cur.execute(
                "INSERT INTO categories (name, description) VALUES (%s, NULL) RETURNING id",
                (name,)
            )
            uuid = cur.fetchone()[0]
            cat_uuid_map[name] = uuid
            print(f"  {uuid}  |  {name}")

        # ── Step 4: Read CSV ──────────────────────────────────────────────────
        print(f"\n[4/5] Reading {INPUT_FILE}...")

        product_rows = []
        skipped = 0

        with open(INPUT_FILE, newline="", encoding="utf-8") as f:
            reader = csv.DictReader(f)
            for row in reader:
                mapped_cat = row.get("mapped_category", "").strip()
                cat_id = cat_uuid_map.get(mapped_cat)
                if not cat_id:
                    skipped += 1
                    continue

                title = row.get("title", "").strip()
                if not title:
                    skipped += 1
                    continue

                raw_cat   = row.get("category", "").strip()
                on_sale   = to_bool(row.get("on_sale", "False"))
                price     = to_num(row.get("original_price", "")) or 0.0
                sale_price = to_num(row.get("sale_price", "")) if on_sale else None
                stock     = 10 if to_bool(row.get("in_stock", "False")) else 0
                images    = to_path_list(row.get("local_image_paths", ""))
                links     = to_path_list(row.get("all_image_urls", ""))
                desc      = build_description(row)
                brand     = extract_brand(title, raw_cat)
                subcat    = MAPPED_CAT_TO_SUBCATEGORY.get(mapped_cat)  # NULL | 'mobile' | 'laptop' | 'computer'

                product_rows.append((
                    title,          # name
                    brand,          # brand
                    cat_id,         # category_id
                    desc,           # description
                    price,          # price
                    sale_price,     # sale_price  (NULL if not on_sale)
                    stock,          # stock
                    False,          # featured
                    on_sale,        # on_sale
                    False,          # has_color_options
                    False,          # has_part_type_options
                    images,         # images  TEXT[]
                    links,          # links   TEXT[]
                    subcat,         # accessory_subcategory: NULL|'mobile'|'laptop'|'computer'
                ))

        print(f"  {len(product_rows)} products ready to insert  ({skipped} skipped).")

        # ── Step 5: Batch insert ──────────────────────────────────────────────
        print(f"\n[5/5] Inserting {len(product_rows)} products (batch size 500)...")

        INSERT_SQL = """
            INSERT INTO products
              (name, brand, category_id, description, price, sale_price,
               stock, featured, on_sale, has_color_options, has_part_type_options,
               images, links, accessory_subcategory, created_at, updated_at)
            VALUES %s
        """
        TEMPLATE = "(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,now(),now())"

        BATCH = 500
        total = len(product_rows)
        inserted = 0

        for i in range(0, total, BATCH):
            batch = product_rows[i : i + BATCH]
            execute_values(cur, INSERT_SQL, batch, template=TEMPLATE)
            inserted += len(batch)
            pct = int(inserted / total * 100)
            print(f"  {inserted}/{total}  ({pct}%)", end="\r")

        conn.commit()
        print(f"\n  All {inserted} products committed.")

        # ── Summary ───────────────────────────────────────────────────────────
        print("\n" + "=" * 60)
        print("  IMPORT COMPLETE — Products per category:")
        print("=" * 60)
        cur.execute("""
            SELECT c.name, COUNT(p.id) AS cnt
            FROM categories c
            LEFT JOIN products p ON p.category_id = c.id
            GROUP BY c.name
            ORDER BY cnt DESC
        """)
        grand_total = 0
        for name, count in cur.fetchall():
            print(f"  {count:6d}  |  {name}")
            grand_total += count
        print("-" * 60)
        print(f"  {grand_total:6d}  |  TOTAL")
        print("=" * 60)
        print("\nYou can now start the app:")
        print("  Terminal 1:  npm run server")
        print("  Terminal 2:  npm run dev")

    except Exception as e:
        conn.rollback()
        print(f"\nERROR — transaction rolled back:\n{e}")
        raise
    finally:
        cur.close()
        conn.close()


if __name__ == "__main__":
    main()
